CREATE TABLE USER (
    ID INT(12) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    AGE INT(5) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL
);

insert into USER (ID, NAME, PASSWORD, AGE, EMAIL) values (NULL, 'Tom', '123', 23, 'tom@mail.com');

DROP TABLE USER;

CREATE TABLE USER (
    ID INT(12) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL
);